#!/usr/bin/env sh
#set -o vi


# change cursor shape for vi-mode
# zle-keymap-select () {
# if [ $KEYMAP = vicmd ]; then
#     printf "\033[2 q"
# else
#     printf "\033[6 q"
# fi
# }
# zle -N zle-keymap-select
# zle-line-init () {
#   zle -K viins
#   printf "\033[6 q"
# }
# zle -N zle-line-init
# /change cursor shape for vi-mode

bindkey -v
# 10ms for key sequences
KEYTIMEOUT=1
