#!/usr/bin/env sh
# export PATH=/usr/local/bin:$PATH
# export PATH=$HOME/local/node/bin:/usr/local/bin:$PATH

export PATH=/usr/local/bin:$PATH
export PATH=./node_modules/.bin:/usr/local/share/npm/bin:$PATH
export PATH="/Users/chris/Workspace/elixir_packages/elixir/bin:$PATH"
